VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "HyperlinkInfo"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'---------------------------------------------------------------------------------------
' Method :
' Author : Mike Morris
' Date   : 07/03/2016
' Purpose:
'---------------------------------------------------------------------------------------
Option
' TODO: Implement HyperlinkInfo class
